neatpix/neatpix/urls.py
"""
neatpix URL Configuration
"""

from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [

    # admin routes:
    url(r'^admin/',
        include(admin.site.urls)),

    # webapp routes:
    url(r'^',
        include('webapp.urls',
                namespace='webapp')),

]

neatpix/webapp/urls.py
from django.conf.urls import url
from views import IndexView, FacebookAuthView,\
                  DashboardView, LogoutView,\
                  PhotosListView, PhotoUploadView,\
                  PhotoServiceView, PhotoUpdateDeleteView


urlpatterns = [

    url(r'^$',
        IndexView.as_view(),
        name='index'),

    url(r'^auth/facebook/$',
        FacebookAuthView.as_view(),
        name='facebook_auth'),

    url(r'^logout/$',
        LogoutView.as_view(),
        name='logout'),

    url(r'^dashboard/$',
        DashboardView.as_view(),
        name='dashboard'),

    url(r'^dashboard/photos/$',
        PhotosListView.as_view(),
        name='photos'),

    url(r'^dashboard/photos/upload/$',
        PhotoUploadView.as_view(),
        name='photo_upload'),

    url(r'^dashboard/photos/(?P<public_id>[\w]+)/$',
        PhotoUpdateDeleteView.as_view(),
        name='photo_update_delete'),

    url(r'^media/photos/(?P<username>[\w\-]+)/' +
        r'(?P<effects>[\w\,]+)/(?P<filename>[\w\-\.]+)$',
        PhotoServiceView.as_view(),
        name='photo_effects_service'),

    url(r'^media/photos/(?P<username>[\w\-]+)/(?P<filename>[\w\-\.]+)$',
        PhotoServiceView.as_view(),
        name='photo_service'),
]

neatpix/webapp/models.py
import os

from django.db import models
from django.db.models.signals import post_delete
from django.contrib.auth.models import User
from django.contrib.humanize.templatetags.humanize import naturalday
from django.template.defaultfilters import title
from django.dispatch import receiver

from utils import genuid, get_photo_upload_path


class SocialProfile(models.Model):
    """
    Represents information about a user
    authenticated via social media.
    """
    FACEBOOK = '1'
    PROVIDERS = (
        (FACEBOOK, 'Facebook'),
    )

    provider = models.SmallIntegerField(choices=PROVIDERS)
    social_id = models.CharField(max_length=255, unique=True)
    photo = models.TextField(blank=True)
    extra_data = models.TextField(blank=True)

    user = models.OneToOneField(User, related_name='social_profile')

    def __unicode__(self):
        return "{}:{}".format(self.provider, self.social_id)


class Photo(models.Model):
    """
    Represents information about photos
    uploaded by the current user.
    """
    image = models.ImageField(upload_to=get_photo_upload_path, max_length=255)
    public_id = models.CharField(default=genuid, max_length=50)
    caption = models.CharField(max_length=255, blank=True)
    effects = models.CharField(max_length=255, blank=True)
    date_created = models.DateTimeField(editable=False, auto_now_add=True)
    date_modified = models.DateTimeField(editable=False, auto_now=True)

    user = models.ForeignKey(User, related_name='photos')

    def serialize(self):
        """
        serializes the photo to a json-style dictionary.
        """
        return {
            'public_id': self.public_id,
            'filename': os.path.basename(self.image.name),
            'username': self.user.username,
            'caption': self.caption,
            'effects': self.effects,
            'date': title(naturalday(self.date_modified)),
        }

    def __unicode__(self):
        return "<Photo: {}-{}".format(self.caption, self.public_id)


@receiver(post_delete, sender=Photo)
def delete_image_file(sender, instance, **kwargs):
    """
    Function that deletes the associated image file
    from the file storage when the Photo instance
    is deleted from the db.
    """
    # get the image file path:
    image_path = instance.image.path
    # delete file from storage:
    if os.path.exists(image_path):
        os.remove(image_path)

neatpix/webapp/forms.py
from django import forms
from django.contrib.auth.models import User

from models import SocialProfile, Photo


class FacebookAuthForm(forms.Form):
    """
    Form for validating and saving Facebook
    user authentication data. Returns the
    existing or created user.
    """

    id = forms.CharField()
    email = forms.EmailField()
    first_name = forms.CharField()
    last_name = forms.CharField()
    photo = forms.CharField(required=False)

    def save(self):
        """
        gets returns the social user with the form data.
        creates one if it does not already exists.
        """
        data = self.cleaned_data
        user = None
        try:
            # get associated user if it exists:
            social_id = data['id']
            social_profile = SocialProfile.objects.get(
                provider=SocialProfile.FACEBOOK,
                social_id=social_id,
            )
            user = social_profile.user

        except SocialProfile.DoesNotExist:
            # Create the user:
            user = User(
                username=data['id'],
                first_name=data['first_name'],
                last_name=data['last_name']
            )
            user.save()

            # Create the user's social_profile:
            social_profile = SocialProfile(
                provider=SocialProfile.FACEBOOK,
                social_id=data['id'],
                photo=data['photo'],
                user=user
            )
            social_profile.save()

        user.backend = 'django.contrib.auth.backends.ModelBackend'
        return user


class PhotoForm(forms.ModelForm):
    """
    Form to handle photo uploads.
    """
    class Meta:
        model = Photo
        fields = ('image', 'caption', 'effects')

neatpix/webapp/views.py
import os
import json
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse
from django.core.context_processors import csrf
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import View
from django.http import HttpResponse

from PIL import Image

from models import Photo
from forms import FacebookAuthForm, PhotoForm
from decorators import json_response
from effects import photo_effects, thumbnail

from neatpix.settings.base import MAX_UPLOAD_SIZE


class LoginRequiredMixin(object):
    """
    View mixin which requires that the user is authenticated.
    """
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(LoginRequiredMixin, self).dispatch(
            request, *args, **kwargs)


class JsonResponseMixin(object):
    """
    View mixin which requires that the user is authenticated.
    """
    @method_decorator(json_response)
    def dispatch(self, request, *args, **kwargs):
        return super(JsonResponseMixin, self).dispatch(
            request, *args, **kwargs)


class IndexView(View):
    """
    The index/login view.
    """
    def get(self, request, *args, **kwargs):
        """
        Renders the index/home view
        """
        # redirect to dashboard if user is already signed in:
        if request.user.is_authenticated():
            return redirect(reverse('webapp:dashboard'))
        # show index view:
        context = {}
        context.update(csrf(self.request))
        return render(self.request, 'webapp/index.html', context)


class FacebookAuthView(JsonResponseMixin, View):
    """
    Logs a user in with their facebook account.
    """
    def post(self, request, *args, **kwargs):
        """
        Logs a user out and redirects to the index view.
        """
        auth_form = FacebookAuthForm(request.POST)
        if auth_form.is_valid():
            # get or create the user:
            user = auth_form.save()
            if user:
                profile = user.social_profile
                profile.extra_data = json.dumps(request.POST)
                profile.save()
                # log the user in:
                login(request, user)
                # return success response:
                return {
                    'status': 'success',
                    'status_code': 200,
                    'loginRedirectURL': reverse('webapp:dashboard'),
                }
        # return error response
        return {'status': 'error', 'status_code': 403, }


class LogoutView(LoginRequiredMixin, View):
    """
    Logs the user out.
    """
    def get(self, request, *args, **kwargs):
        """
        Logs a user out and redirects to the index view.
        """
        logout(request)
        return redirect(reverse('webapp:index'))


class DashboardView(LoginRequiredMixin, View):
    """
    Represents the signed in users' dashboard/workspace view.
    """
    def get(self, request, *args, **kwargs):
        """
        Renders the dashboard view.
        """
        # show index view:
        context = {
            'photo_effects': photo_effects,
        }
        context.update(csrf(self.request))
        return render(self.request, 'webapp/dashboard.html', context)


class PhotosListView(JsonResponseMixin, LoginRequiredMixin, View):
    """
    View to fetch the list of photos.
    """
    def get(self, request, *args, **kwargs):
        """
        Returns a JSON list of photos uploaded
        by the current user.
        """
        photos = Photo.objects.filter(user=request.user)\
                              .order_by('date_created')\
                              .all()
        photos = [photo.serialize() for photo in photos]
        return {
            'status': 'success',
            'status_code': 200,
            'data': photos,
        }


class PhotoUploadView(JsonResponseMixin, LoginRequiredMixin, View):
    """
    View to handle photo uploads.
    """
    def post(self, request, *args, **kwargs):
        """
        Handles the upload of photos and returns
        a JSON serialization of the uploaded photo.
        """
        photoForm = PhotoForm(request.POST, request.FILES)

        if photoForm.is_valid():
            # check that the file size is valid:
            image_file_size = photoForm.files['image'].size
            if image_file_size <= MAX_UPLOAD_SIZE:
                # save the photo and image file:
                photo = photoForm.save(commit=False)
                # set the default caption and user:
                photo.caption = photo.image.name
                photo.user = request.user
                photo.save()
                # return the serialized photo:
                return {
                    'status': 'success',
                    'status_code': 200,
                    'photoData': photo.serialize(),
                }

        # return error response
        return {'status': 'invalid', 'status_code': 403, }


class PhotoUpdateDeleteView(JsonResponseMixin, LoginRequiredMixin, View):
    """
    View to handle changes to photos such as updating the
    applied effects, the caption or deleting it altogethter.
    """
    def post(self, request, *args, **kwargs):
        """
        Handles the updating of photos and returns
        a JSON serialization of the updated photo.
        Note, this view cannot update the associated
        image file.
        """
        public_id = kwargs.get('public_id')
        photo = get_object_or_404(Photo, public_id=public_id)
        photoForm = PhotoForm(request.POST, instance=photo)
        if photoForm.is_valid():
            # save the photo:
            photo = photoForm.save()
            # return the serialized photo:
            return {
                'status': 'success',
                'status_code': 200,
                'photoData': photo.serialize(),
            }
        # return error response
        return {'status': 'invalid', 'status_code': 403, }

    def delete(self, request, *args, **kwargs):
        """
        Handles the deleting of photos.
        Note, the actual deletion of the associated
        image file is handled in the post_delete
        function defined in the models module.
        """
        public_id = kwargs.get('public_id')
        photo = get_object_or_404(Photo, public_id=public_id)
        photo.delete()
        # return error response
        return {'status': 'success', 'status_code': 200, }


class PhotoServiceView(View):
    """
    View to handle serving uploaded photos with
    effects (optional) applied.
    """
    content_type = "image/jpg"
    output_format = "JPEG"

    def get(self, request, *args, **kwargs):
        """
        Accepts a photo's public_id and optionally a list of
        effects to apply. Returns the image (FileResponse)
        with the applied effects.
        """
        # use the captured image specs from the url
        # to get the associated photo instance:
        filename = kwargs.get('filename')
        effects = kwargs.get('effects')
        public_id, ext = os.path.splitext(filename)
        photo = get_object_or_404(Photo, public_id=public_id)

        # get a pillow image instance for the photo:
        image = Image.open(photo.image.path)

        # convert image to thumbnail size if specified:
        if request.GET.get('thumbnail') == 'true':
            image = thumbnail(image)

        # apply any specified effects:
        if effects:
            effects = effects.split(',')
            # get the matching effects:
            is_matching_effect = lambda effect: effect[0] in effects
            matching_effects = filter(is_matching_effect, photo_effects)
             # apply each matching effect to the image:
            for effect in matching_effects:
                image = effect[1](image)

        # save the image to a FileResponse instance:
        response = HttpResponse(content_type=self.content_type)
        image.save(response, self.output_format)

        # trigger download if specified:
        if request.GET.get('download') == 'true':
            response['Content-Disposition'] = 'attachment; filename="{}.jpg"'\
                                              .format(photo.public_id)
        return response

neatpix/webapp/templates/webapp/dashboard.html
{% extends "base.html" %}
{% load static %}

{% block window_title %}Dashboard{% endblock window_title %}

{% block main %}
  <div class="dashboard flex column-layout">
    <div class="header-bar flex row-layout vertical align-center">
      <div class="brand">
        <a href=""><img src="{% static 'img/logo-sm-white.png' %}"></a>
      </div>
      <div class="header-options fill flex row-layout align-middle-right">
        <span>Logged in as <span class="emphasis">{{ request.user.first_name }} {{ request.user.last_name }}</span></span>
        <a href="https://facebook.com" target="_blank" class="profile-photo imgLiquidFill imgFilled">
          <img src="{{ request.user.social_profile.photo }}">
        </a>
        <a href="{% url 'webapp:logout' %}" class="btn-action-alt" id="logout-btn">Log Out</a>
      </div>
    </div>
    <div class="workspace fill flex row-layout"> 
      
      <div class="photo-list fill flex column-layout">
        
        <div class="header flex row-layout vertical align-center">
          <div class="title fill flex row-layout align-middle-left">
            <h3 class="section-label">My Photos</h3>
          </div>
          <div class="divider-v divider-shaded"></div>
          <button class="btn-action add-photo" title="Upload a Photo"><i class="fa fa-plus fa-lg"></i></button>
        </div>
        
        <div class="divider divider-shaded"></div>
        
        <div class="content fill flex column-layout">
          <ul class="list fill scrollable-container">
            <div class="scrollable-y">
              <!-- photo-list items go here -->
            </div>
          </ul>
          <div class="list-status">
            <!-- photo-list statuses go here -->
          </div>
        </div>

      </div>

      <div class="divider-v"></div>

      <div class="editor fill flex column-layout">
        
        <div class="header flex row-layout align-middle-right">
          <div class="title">
            <span class="caption section-label"></span><span class="effects subtle"></span>
          </div>
          <div class="options fill flex row-layout align-middle-right">
            <button class="btn-action undo" title="Undo last effect"><i class="fa fa-undo fa-fw"></i>Undo</button>
            <button class="btn-action reset" title="Reset to original image"><i class="fa fa-undo fa-flip-vertical fa-fw"></i>Reset</button>
            <button class="btn-action save-changes" title="Save changes to cloud"><i class="fa fa-check fa-fw"></i>Save Changes</button>
            <button class="btn-action cancel" title="Close this editor"><i class="fa fa-times fa-fw"></i>Cancel</button>
          </div>
        </div>

        <div class="divider divider-shaded"></div>

        <div class="stage fill image-wrapper imgLiquidFill imgFitted">
          <img src="">
        </div>

        <div class="divider divider-shaded"></div>

        <div class="effects-section">
          <ul class="list scrollable-container">
            <div class="scrollable-x">
              <!-- efffect-list items go here -->
              {% for effect in photo_effects %}
                {% include "webapp/snippet_effect_card.html" %}
              {% endfor %}
            </div>
          </ul>
          <div class="effects-header flex row-layout align-middle-center">
            <span class="directive fill">Select effect(s) to apply by clicking on them:</span>
            <div class="cumulative-effects">
              <input type="checkbox" id="cumulative-cbox" value="useCumulativeEffects">
              <label for="cumulative-cbox">Use cumulative effects</label>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
{% endblock main %}

{% block generic_snippets %}
  {% include "webapp/snippet_photo_card.html" %}
{% endblock generic_snippets %}

neatpix/webapp/templates/webapp/index.html
{% extends "base.html" %}
{% load static %}

{% block main %}
  <main class="index-page">

    <div class="bg-img imgLiquidFill imgFilled">
      <img src="{% static 'img/collage.jpg' %}">
    </div>

    <div class="page-content flex column-layout">

      <section class="hero fill flex column-layout horizontal align-middle vertical align-center">
        <div class="brand"><img src="{% static 'img/logo-lg-white.png' %}"></div>
        <h2 class="slogan">upload. prettify. share.</h2>
        <div class="call-to-action">
          <button class="btn-action-alt" id="facebook-login-action"><i class="fa fa-facebook-official fa-fw"></i> Log in with Facebook</button>
        </div>
        <div class="status">
          <p id="facebook-login-status"></p>
          <form id="login-csrf">{% csrf_token %}</form>
        </div>

      </section>

      <footer class="footer flex column-layout horizontal align-middle vertical align-center">
        <p class="copyright">Copyright ©{% now "Y" %}. A <a href="http://github.com/andela-uawili/photo-editing-application">project</a> by <a href="http://github.com/andela-uawili/">Awili Uzo</a> from <a href="http://andela.com">Andela</a>. #TIA</p>
      </footer>

    </div>

  </main>
{% endblock main %}

neatpix/webapp/templates/webapp/snippet_effect_card.html
{% load static %}

<li class="effect-card" data-effect-name="{{ effect.0 }}">
  <div class="flex column-layout">
    <div class="image-wrapper imgLiquidFill imgFilled">
      <img src="">
    </div>
    <div class="details flex row-layout align-middle-center">
      <div class="name">{{ effect.0|title }}</div>
    </div>
  </div>
</li>

neatpix/webapp/templates/webapp/snippet_photo_card.html
{% load static %}

<li class="photo-card" id="generic-photo-card">
  <div class="upload flex column-layout vertical align-center">
    <div class="photo-icon imgLiquidFill imgFilled">
      <img src="{% static 'img/photo-icon.png' %}">
    </div>
    <p class="instruction">Drag and drop OR<br><a href="" class="accent browse-file">Click here</a> to browse for image file.</p>
    <form class="upload-form" method="POST" action="{% url 'webapp:photo_upload'%}" enctype="multipart/form-data">
      {% csrf_token %}
      <input type="file" name="image" />
    </form>
    <p class="file-info"></p>
    <div class="call-to-action">
      <button class="btn-action upload-photo disabled"><i class="fa fa-cloud-upload fa-fw"></i> Upload</button>
    </div>
  </div>

  <div class="uploading flex column-layout">
    <p class="filename"></p>
    <div class="status">
      <span class="message"></span>
      <span class="value"></span>
    </div>
    <div class="progress-bar">
      <span class="total"></span>
      <span class="progress"></span>
    </div>
  </div>

  <div class="uploaded flex column-layout">

    <div class="image-wrapper imgLiquidFill imgFilled">
      <a class="apply-effects" href=""><img src=""></a>
    </div>
    <div class="details flex row-layout vertical align-center">
      <div class="caption"><span></span></div>
      <div class="date fill"><span></span></div>
    </div>
    <div class="divider"></div>
    <div class="actions flex row-layout horizontal align-middle vertical align-center">
      <button class="btn-action subtle apply-effects" title="Apply Effects"><i class="fa fa-magic fa-lg"></i></button>
      <button class="btn-action subtle edit-caption" title="Edit Caption"><i class="fa fa-font fa-lg"></i></button>
      <button class="btn-action subtle share-photo" title="Share on Facebook"><i class="fa fa-facebook-square fa-lg"></i></button>
      <button class="btn-action subtle download-photo" title="Download"><i class="fa fa-download fa-lg"></i></button>
      <button class="btn-action subtle delete-photo" title="Delete"><i class="fa fa-trash fa-lg"></i></button>
    </div>

  </div>

  <div class="delete-overlay overlay flex column-layout align-middle-center">
    <div class="icon">
      <i class="fa fa-trash fa-3x"></i>
    </div>
    <p class="directive">Are you sure?<br>Click the button below to confirm.</p>
    <div class="call-to-action">
      <button class="btn-action confirm-delete-photo"><i class="fa fa-trash fa-fw"></i> Delete Photo</button>
    </div>
  </div>

  <div class="caption-overlay overlay flex column-layout align-middle-center">
    <p class="directive">
      <span>Caption this Photo:</span>
    </p>
    <div><input type="text" name="caption" class="caption-input sleek-textbox"></div>
    <div class="call-to-action">
      <button class="btn-action save-caption"><i class="fa fa-check fa-fw"></i> Save Caption</button>
    </div>
  </div>

  <form class="csrf-form" method="" action="">{% csrf_token %}</form>
  
  <button class="btn-icon cancel-btn subtle" title="Cancel">
    <i class="fa fa-times fa-lg"></i>
  </button>
</li>